easy_admin:
    entities:
        Category:
            class: App\Entity\Category
            list:
                fields:
                    - id
                    - name
                    - type
                    - parent
            form:
                fields:
                    - name
                    - description
                    - { property: type, type: choice, type_options: { expanded: true, choices: '%game_categories%' } }
                    - { property: parent, type_options: { choice_label: name } }
