easy_admin:
    entities:
        User:
            class: App\Entity\User
            list:
                fields:
                    - id
                    - username
                    - email
                    - resetToken
            form:
                fields:
                    - username
                    - email
                    - { property: roles, type: choice, type_options: { expanded: true, multiple: true } }
                    - resetToken
