easy_admin:
    entities:
        User:
            class: App\Entity\User
            list:
                fields:
                    - id
                    - username
                    - email
                    - resetToken
            form:
                fields:
                    - username
                    - email
                    - resetToken
                    - { property: topics, type_options: { choice_label: title } }
