easy_admin:
    site_name: 'BDG - Admin'
imports:
    - { resource: ./admin/user.yaml }
    - { resource: ./admin/category.yaml }
    - { resource: ./admin/location.yaml }
    - { resource: ./admin/persona.yaml }
