# Read the documentation: https://symfony.com/doc/current/bundles/FOSCKEditorBundle/index.html

twig:
    form_themes:
        - '@FOSCKEditor/Form/ckeditor_widget.html.twig'

fos_ck_editor:
    configs:
        role_play_conf:
            toolbar: "role_play_toolbar"
    toolbars:
        configs:
            role_play_toolbar:
                - [ "Bold", "Italic", "Underline", "Strike", "Subscript", "Superscript", "RemoveFormat", "-", "Maximize" ]
                - "/"
                - [ "Blockquote", "JustifyLeft", "JustifyCenter", "JustifyRight", "JustifyBlock", "-", "Image", "HorizontalRule" ]
                - "/"
                - [ "Styles", "Format", "FontSize", "TextColor" ]
