# Read the documentation: https://symfony.com/doc/current/bundles/FOSCKEditorBundle/index.html
fos_ck_editor:
    base_path: "build/ckeditor"
    js_path:   "build/ckeditor/ckeditor.js"
    configs:
        role_play_conf:
            toolbar: "role_play_toolbar"
    toolbars:
        configs:
            role_play_toolbar:
                - [ "Bold", "Italic", "Underline", "Strike", "Subscript", "Superscript", "RemoveFormat", "-", "Maximize" ]
                - "/"
                - [ "Blockquote", "JustifyLeft", "JustifyCenter", "JustifyRight", "JustifyBlock", "-", "Image", "HorizontalRule" ]
                - "/"
                - [ "Styles", "Format", "FontSize", "TextColor" ]
