framework:
    workflows:
        game_life:
            type: 'state_machine'
            audit_trail:
                enabled: true
            marking_store:
                type: 'method'
                property: 'state'
            supports:
                - App\Entity\Game
            initial_marking: draft
            places:
                - draft
                - published
                - in_progress
                - completed
            transitions:
                publish:
                    from: draft
                    to:   published
                start:
                    from: published
                    to:   in_progress
                finish:
                    from: in_progress
                    to:   completed
